# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Biodiversity - Ecological Patterns and Processes
email: skmorgane@ufl.edu
description: > # this means to ignore newlines until "baseurl:"
  Morgan Ernest's course on Biodiversity: Ecological Patterns and Processes.
  Taught at the University of Florida in Fall 2016.
baseurl: "/biodiversity-course" # the subpath of your site, e.g. /blog
url: "https://skmorgane.github.io/biodiversity-course" # the base hostname & protocol for your site
twitter_username: weecology
github_username:  skmorgane

# Build settings
markdown: kramdown
